---
# Database information for production
prod:
  schema: 'AlarmClock'
  adapter: 'mysql'
  username: 'alarm'
  password: 'some_pass'
  location: 'localhost'
# Database information for test - see alarm_app_spec.rb
test:
  schema: 'AlarmClock'
  adapter: 'mysql'
  username: 'alarm'
  password: 'some_pass'
  location: 'localhost'